`Pixelize`
---

**BROKEN**

In [1]:
import numpy as np

def convolve_2d(image: np.ndarray, kernel, mode: str = 'constant') -> np.ndarray:
    # boundaries for kernel window
    kernel_y, kernel_x = kernel.shape
    # range for loops
    image_y, image_x = image.shape
    # dynamic pad sizing based on kernel dimensions
    pad_y, pad_x = kernel_y // 2, kernel_x // 2 
    # init output matrix 
    filtered_image = np.zeros_like(a = image, dtype = np.float32) 
    # add padding                                    
    paddded_image = np.pad(array = image, pad_width = (( pad_y, pad_x ), ( pad_x, pad_y )), mode = mode)

    # Convolve
    for y in range(image_y):
        for x in range(image_x):
            # Sliding frame
            window = paddded_image[ y : y + kernel_y, x : x + kernel_x ]
            # Apply filter
            filtered_image[ y, x ] = np.sum(window * kernel)
    return filtered_image

def convolve_3d(image: np.ndarray, kernel, mode: str = 'constant') -> np.ndarray:
    # boundaries for kernel window
    kernel_y, kernel_x, _ = kernel.shape
    # range for loops
    image_y, image_x, _ = image.shape
    # dynamic pad sizing based on kernel dimensions
    pad_y, pad_x = kernel_y // 2, kernel_x // 2 
    # init output matrix 
    filtered_image = np.zeros_like(a = image, dtype = np.float32) 
    # add padding                                    
    paddded_image = np.pad(array = image, pad_width = (( pad_y, pad_y ), ( pad_x, pad_x ), (0, 0)), mode = mode)

    # Convolve
    for y in range(image_y):
        for x in range(image_x):
            # Sliding frame
            window = paddded_image[ y : y + kernel_y, x : x + kernel_x ]
            # Apply filter
            filtered_image[ y, x ] = np.sum(window * kernel, axis = (0, 1))
    return filtered_image

def convolve(image: np.ndarray, kernel: np.ndarray, mode: str = 'constant') -> np.ndarray:
    if isinstance(kernel, np.matrix):
        kernel = np.array(object = kernel, dtype = np.float32)

    # 2D or 3D
    if image.ndim == 2:
        return convolve_2d(image, kernel, mode)
    else:
        return convolve_3d(image, kernel, mode)
    

def pixelize(image: np.ndarray, bit: int = 64) -> np.ndarray:
    # dynamicaly handle arg 'kernel': matrix or size
    pixel_kernel = np.ones(shape = (bit, bit), dtype = np.float32) / bit**2

    if image.ndim == 3:  # Color image
        pixel_kernel = np.expand_dims(pixel_kernel, axis=-1)

    return convolve(image, pixel_kernel, 'mean') 

`Mean Filter`
---

In [54]:
import numpy as np

def mean_filter(image, size = 3):

    image_y, image_x = image.shape
    padded_image = np.pad(array = image, pad_width = (size // 2), mode = 'constant', constant_values = 0)
    filtered_image = np.zeros_like(a = image, dtype = np.float32)
    kernel = np.ones(shape = (size, size), dtype = np.float32) / (size**2)

    # Slicing out the 3x3 regions
    # Get all 3x3 regions at once using advanced slicing
    for y in range(size):
        for x in range(size):
            # Add each of the 3x3 shifted slices to the output
            filtered_image += padded_image[ y : y + image_y, x : x + image_x] * kernel[ y, x]

    return filtered_image

matrix = np.array([[10, 11, 9, 25, 22],
                   [8, 10, 9, 26, 28],
                   [9, 99, 9, 24, 25],
                   [11, 11, 12, 23, 22],
                   [10, 11, 9, 22, 25]], dtype = np.float32)

print(mean_filter(matrix))  

[[ 4.3333335  6.3333335 10.        13.222221  11.222221 ]
 [16.333334  19.333334  24.666666  19.666666  16.666666 ]
 [16.444445  19.777777  24.777777  19.777779  16.444445 ]
 [16.777777  20.11111   24.444445  19.000002  15.666667 ]
 [ 4.7777777  7.111111   9.777778  12.555555  10.222222 ]]


`Median Filter`
---

In [52]:
import numpy as np
from numpy.typing import ArrayLike

def median_filter(image: np.ndarray, kernel_size: ArrayLike) -> np.ndarray:

    # range for loops
    image_y, image_x = image.shape 

    # init output matrix 
    filtered_image = np.zeros_like(a = image, dtype = np.float32) 

    # add padding                                    
    paddded_image = np.pad(array = image, pad_width = (kernel_size // 2) , mode = 'constant', constant_values = 0)

    for y in range(image_y):
        for x in range(image_x):
            # sliding window
            window = paddded_image[ y : y + kernel_size, x : x + kernel_size ]
            # apply median filter
            filtered_image[ y, x ] = np.median(window)
    
    return filtered_image

matrix = np.array([[10, 11, 9, 25, 22],
                   [8, 10, 9, 26, 28],
                   [9, 99, 9, 24, 25],
                   [11, 11, 12, 23, 22],
                   [10, 11, 9, 22, 25]], dtype = np.float32)

print(median_filter(matrix)) 

[[ 0.  9.  9.  9.  0.]
 [ 9.  9. 11. 24. 24.]
 [ 9. 10. 12. 23. 23.]
 [10. 11. 12. 22. 22.]
 [ 0. 10. 11. 12.  0.]]


`Convolve`
---

In [1]:
import numpy as np

def convolve_2d(image: np.ndarray, kernel, mode: str = 'constant') -> np.ndarray:
    # boundaries for kernel window
    kernel_y, kernel_x = kernel.shape
    # range for loops
    image_y, image_x = image.shape
    # dynamic pad sizing based on kernel dimensions
    pad_y, pad_x = kernel_y // 2, kernel_x // 2 
    # init output matrix 
    filtered_image = np.zeros_like(a = image, dtype = np.float32) 
    # add padding                                    
    paddded_image = np.pad(array = image, pad_width = (( pad_y, pad_x ), ( pad_x, pad_y )), mode = mode)

    # Convolve
    for y in range(image_y):
        for x in range(image_x):
            # Sliding frame
            window = paddded_image[ y : y + kernel_y, x : x + kernel_x ]
            # Apply filter
            filtered_image[ y, x ] = np.sum(window * kernel)
    return filtered_image

def convolve_3d(image: np.ndarray, kernel, mode: str = 'constant') -> np.ndarray:
    # boundaries for kernel window
    kernel_y, kernel_x, _ = kernel.shape
    # range for loops
    image_y, image_x, _ = image.shape
    # dynamic pad sizing based on kernel dimensions
    pad_y, pad_x = kernel_y // 2, kernel_x // 2 
    # init output matrix 
    filtered_image = np.zeros_like(a = image, dtype = np.float32) 
    # add padding                                    
    paddded_image = np.pad(array = image, pad_width = (( pad_y, pad_y ), ( pad_x, pad_x ), (0, 0)), mode = mode)

    # Convolve
    for y in range(image_y):
        for x in range(image_x):
            # Sliding frame
            window = paddded_image[ y : y + kernel_y, x : x + kernel_x ]
            # Apply filter
            filtered_image[ y, x ] = np.sum(window * kernel, axis = (0, 1))
    return filtered_image

def convolve(image: np.ndarray, kernel: np.ndarray, mode: str = 'constant') -> np.ndarray:
    if isinstance(kernel, np.matrix):
        kernel = np.array(object = kernel, dtype = np.float32)

    # 2D or 3D
    if image.ndim == 2:
        return convolve_2d(image, kernel, mode)
    else:
        return convolve_3d(image, kernel, mode)


matrix = np.array([[10, 11, 9, 25, 22],
                   [8, 10, 9, 26, 28],
                   [9, 99, 9, 24, 25],
                   [11, 11, 12, 23, 22],
                   [10, 11, 9, 22, 25]], dtype = np.float32)

array = np.array([[11, 15, 20, 21, 22],
                  [8, 19, 17, 22, 23],
                  [7, 14, 18, 21, 25],
                  [10, 15, 15, 19, 54],
                  [11, 12, 11, 17, 22]], dtype = np.float32)
kernel = np.array([[1, 1, 1],
                   [1, 2, 1],
                   [1, 1, 1]], dtype=np.float32) # Gaussian blur kernel

kernel /= np.sum(kernel) # Normalise kernel
array /= 255.0
print(convolve(array, kernel))


[[ 6.4       10.5       13.400001  14.600001  11.       ]
 [ 8.2       14.8       18.4       21.1       15.700001 ]
 [ 8.        13.700001  17.800001  23.5       18.900002 ]
 [ 7.8999996 12.800001  15.7       22.1       21.2      ]
 [ 5.9        8.6       10.        15.5       13.4      ]]
